In [52]:
import pandas as pd

In [53]:
df = pd.read_csv("/content/drive/MyDrive/Data logger Januari 2024 /Unit Amikom/Unit 7/Unit 7 fix/20230228_PM5330.csv")
df.head()

,Time Stamp,V R-S,V S-T,V R-T,V R-N,V S-N,V T-N,IA,IB,IC,...,H11,Frekuensi,Max Current,Max Current Unbalance,Max Voltage L-L,Max Voltage Unbalance,Max THD I,Active Energy,Unnamed: 30,Unnamed: 31
0,2023-03-05 00:00:18,388.79,392.29,388.52,224.88,226.38,224.16,6.22,6.06,5.09,...,NAN,50.03,211.3,167.18,409.01,100.0,22.99,423884470,NaN,NaN
1,2023-03-05 00:00:28,388.94,392.40,388.48,224.85,226.45,224.20,6.20,6.10,5.10,...,NAN,50.03,211.3,167.18,409.01,100.0,22.99,423884481,NaN,NaN
2,2023-03-05 00:00:38,388.63,392.08,388.36,224.87,226.29,224.05,6.26,6.17,5.14,...,NAN,50.02,211.3,167.18,409.01,100.0,22.99,423884488,NaN,NaN
3,2023-03-05 00:00:48,388.96,392.34,388.61,225.07,226.48,224.16,6.29,6.19,5.15,...,NAN,50.04,211.3,167.18,409.01,100.0,22.99,423884499,NaN,NaN
4,2023-03-05 00:00:58,388.91,392.35,388.57,225.03,226.47,224.15,6.26,6.20,5.20,...,NAN,50.04,211.3,167.18,409.01,100.0,22.99,423884507,NaN,NaN

In [54]:
df['Time Stamp'] = pd.to_datetime(df['Time Stamp'])
df['date'] = df['Time Stamp'].dt.date

In [55]:
for tanggal in df['date'].unique():
    data_harian = df[df['date'] == tanggal]
    nama_file = f'data_logger_{tanggal}.csv'
    data_harian.to_csv(nama_file, index=False)